import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link";
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '../component/Header'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Shoma Kato</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <p>ポートフォリオサイトです。</p>
        <div>
          <Link href={"portfolio"}>・ポートフォリオ</Link>
        </div>
        <div>
          <Link href={"blog"}>・ブログ</Link>
        </div>
      </main>
    </>
  )
}
