import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link";
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '../components/Header'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Shoma Kato</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <Header />
        <p>ポートフォリオサイトです。</p>

        <div>
          <ul>
            <li><Link href={"blog"}>→blogを見る</Link></li>
            <li><Link href={"portfolio"}>→worksを見る</Link></li>
          </ul>
        </div>
        <p className="mt-4">自己紹介</p>
        <p>
          shomaと申します。<br />
          ソフトウェア開発をメインに制作活動をしています。<br />
          WEBのフロントエンド実装を軸にUI/UXの制作をしています。<br />
          また、インディーゲーム制作もしています。
        </p>

        <div className="mt-4">
          <div>リンク</div>
          {/* <ul>
            <li><a href="https://twitter.com/DonutsHunter" target="_blank">Twitter</a></li>
          </ul> */}
        </div>
      </main>
    </>
  )
}
