import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link";
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { client } from "../libs/client";
import Header from '../components/Header'
import Footer from '../components/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ portfolio, blog }) {
  return (
    <>
      <Head>
        <title>Shoma Kato</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <Header />

        <div>
          <div className='mt-4'>
            <h2 className='text-xl'>Works</h2>
            <ul>
              {portfolio.map((portfolio) => (
                <li key={portfolio.id}>
                  <Link href={`/portfolio/${portfolio.id}`} className='underline'>{portfolio.title}</Link>
                </li>
              ))}
            </ul>
            <div>...</div>
            <div>
              <Link href={"/portfolio"} className='underline'>→works一覧を見る</Link>
            </div>
          </div>

          <div className='mt-4'>
            <h2 className='text-xl'>Blog</h2>
            <ul>
              {blog.map((blog) => (
                <li key={blog.id}>
                  <Link href={`/blog/${blog.id}`} className='underline'>{blog.title}</Link>
                </li>
              ))}
            </ul>
            <div>...</div>
            <div>
              <Link href={"/blog"} className='underline'>→blog一覧を見る</Link>
            </div>
          </div>
        </div>
        <p className="mt-4 text-xl">自己紹介</p>
        <p>
          shomaです。<br />
          オンスクリーンデザイン/開発をメインに制作活動をしています。<br />
          WEBのフロントエンド実装を軸にUI/UXの制作からNext.js、React.jsの実装を一貫して担当いたします。<br />
          インディーゲーム制作やアプリ制作などもしています。
        </p>

        <ul className="mt-4">
          <li>2021~2023現在：株式会社ハンドサム</li>
          <li>2020~2021：株式会社ドットインストール</li>
          <li>2020：多摩美術大学統合デザイン学科卒業</li>
        </ul>

        <Footer />
      </main>
    </>
  )
}


// データをテンプレートに受け渡す部分の処理を記述します
export const getStaticProps = async () => {
  const portfolioData = await client.get({ endpoint: "portfolio" });
  const blogData = await client.get({ endpoint: "blog" });
  return {
    props: {
      portfolio: portfolioData.contents,
      blog: blogData.contents,
    },
  };
};
